### ISSUE TITLE
Hi! Can you provide documentation in English?

### ISSUE THREAD

**Issue by IMSUVEN** [TextAliveJp/textalive-app-api#1]

**Comment by arcatdmz** [comment]
Hi @IMSUVEN, thank you for your interest!

I'm the core developer of `textalive-app-api` and would love to add English version of the documentation. Although, it might take some time.

Meanwhile, please note that the API documentation is already written in both Japanese and English.

https://developer.textalive.jp/packages/textalive-app-api/classes/player.html

Some example projects also have English comments. Please feel free to fork them, play with them, and perhaps send PR if you find any issue.

https://github.com/TextAliveJp/textalive-app-basic/

Regarding the Magical Mirai programming contest, there's nothing that prevents people abroad (outside Japan) from their applications. As such, I'm looking forward to many applications and am happy to help out.

**Comment by arcatdmz** [comment]
- Related issue: https://github.com/TextAliveJp/textalive-app-basic/issues/1
- Translated README file: https://github.com/TextAliveJp/textalive-app-basic/blob/master/README.en.md

**Comment by IMSUVEN** [comment]
Thank you
