### ISSUE TITLE
突然、歌詞情報が取得できなくなった。

### ISSUE THREAD

**Issue by omegarin02** [TextAliveJp/textalive-app-api#10]
昨日の障害の影響かは分かりませんが、歌詞の取得ができなくなりました。（ご対応中でしたらすみません）
歌詞情報を取得してるだろうと思われる処理で、504Errorが返ってくるので、
サーバに問題があるのではないかと思いissueを書いております。
サーバの問題であれば、私の方では何もできないですが、そうでない場合どのような原因が考えらえるか、ご教授いただけないでしょうか。

ご参考までに具体的なエラーと動作環境を添付いたします。
※Tokenが含まれてそうな出力であったので、[マジカルミライのサポートページ](https://developer.textalive.jp/events/magicalmirai10th/)を開いた際のエラーを添付していますが、私のスクリプトでも同様のエラーがでます。
### エラー
```
Access to XMLHttpRequest at 'https://api.textalive.jp/' from origin 'https://cdpn.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
```
Failed to load resource: net::ERR_FAILED
```
```
Access to XMLHttpRequest at 'https://api.textalive.jp/etc/lyrics/token?lyricId=53718' from origin 'https://cdpn.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
```
Failed to load resource: net::ERR_FAILED
```
```
Access to XMLHttpRequest at 'https://api.textalive.jp/etc/license?url=https:%2F%2Fpiapro.jp%2Ft%2FHq9Y&token=-1608991360&skipOptoutCheck=true' from origin 'https://cdpn.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
```
GET https://api.textalive.jp/etc/license?url=https:%2F%2Fpiapro.jp%2Ft%2FHq9Y&token=-1608991360&skipOptoutCheck=true net::ERR_FAILED 504
```

### 動作環境
- OS
  - Windows10
- httpサーバ
  - node v16.14.2 のhttp-server
- ブラウザ
  - vivaldiブラウザ
  - Windows Edgeブラウザ
- 回線
  - 光回線   

※自宅回線の問題かと思い、4G回線でマジカルミライのサポートページのサンプルを開いてみましたが
　症状は同じだったため、回線の影響でもないと考えております。

以上です。よろしくお願いいたします。

**Comment by omegarin02** [comment]
本日試したところ、改善されておりました。
ご対応ありがとうございました。

**Comment by omegarin02** [comment]
時間空けて、やってみたらまた駄目になりました。

**Comment by srn221B** [comment]
上記エラーについてですが、
しばらく時間を置くと`net::FAILED`のエラーは解消され、TextAliveAppは利用できるようなります。
ですが以下のエラーが出て歌詞は表示されない状況です。（マジカルミライのサポートページのサンプルでも同じ症状でした）
```
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). 
```
恐れ入りますがよろしくお願いいたします。

**Comment by omegarin02** [comment]
ご対応ありがとうございます。
歌詞の情報は現状取れない旨承知いたしました。
復旧次第、お知らせいただければ幸いです。

よろしくお願いいたします。

**Comment by srn221B** [comment]
あ。。。勝手に便乗してすみません。私は対応者ではないです(not-assigned)

**Comment by omegarin02** [comment]
あ、そうだったんですね。。。
でも、他の方も困ってることが分かってある意味安心しました。
早く復旧してくれるといいですね

**Comment by arcatdmz** [comment]
みなさま、大変ご迷惑ご心配をおかけして申し訳ありませんでした。
Twitterでもご報告いただいており、対応した結果、今のところは復旧しております。（今後はGitHubも頻繁に確認するようにします。）

https://twitter.com/TextAliveJp/status/1535650762574929922
