### ISSUE TITLE
[Feature Request]歌詞の読み情報の取得

### ISSUE THREAD

**Issue by Rozelin-dc** [TextAliveJp/textalive-app-api#11]
フレーズや単語の情報と同様に、歌詞の読みと発声タイミングの情報を一音ずつひらがな又はローマ字で取得できるような機能が欲しいです

**Comment by arcatdmz** [comment]
TextAlive App API のご利用ありがとうございます。

文字単位の情報でしたら[単語](https://developer.textalive.jp/packages/textalive-app-api/interfaces/IWord.html)の[子 (children プロパティ)](https://developer.textalive.jp/packages/textalive-app-api/interfaces/IWord.html#children)として [IChar](https://developer.textalive.jp/packages/textalive-app-api/interfaces/IChar.html) 型の情報が取れるようになっています。

この型のインスタンスを再生時刻の情報から探すには、 [findChar](https://developer.textalive.jp/packages/textalive-app-api/interfaces/IVideo.html#findChar) メソッドが使えます。（`player.video.findChar(player.timer.position)` などとします。）

文字自体は [IChar.text](https://developer.textalive.jp/packages/textalive-app-api/interfaces/IChar.html#text) で取得できますが、大変恐縮ながら「読み」の情報は取得できません。

- TextAliveは歌詞そのものを配信しない、という原則があるためなので、機能追加も残念ながら難しいです。
- 歌詞は、リリックアプリを実行するクライアントのWebブラウザが配信元サイト（例えば、マジカルミライのプログラミング・コンテストの対象楽曲の場合はピアプロ）から直接取得しています。
- したがって、配信元サイトが歌詞の読み配信に対応した際には、機能追加できる可能性があります。

マジカルミライのプログラミング・コンテストに参加される場合は、お手数ではありますが、サポートしたい楽曲について文字と読みの対応表を作ってご対応いただく方法を採ることならできるかもしれません。

**Comment by Rozelin-dc** [comment]
休日にもかかわらず素早い対応ありがとうございます。

読みの情報が取得できない件、了解しました。別の方法で読みを取得する方法を検討します。
