### ISSUE TITLE
Player を複数生成し、requestPlay() を実行すると楽曲が再生されないことがある

### ISSUE THREAD

**Issue by ya2ha4** [TextAliveJp/textalive-app-api#12]
textalive-app-api (ver.0.3.2) を使用している際に下記の症状が発生しています。

* 症状
new Player() を実行してから onTimerReady() のイベントリスナーが発生するまでに別の Player を生成すると、requestPlay() を実行しても楽曲が再生されません。
この時、すべての Player.requestPlay() は true を返しています。

* 再現方法
https://github.com/ya2ha4/TextAliveAppAPI_VerificationCode_2023_11_ver1 にて再現コードを用意していますのでご確認いただけますでしょうか。

* 回避方法
症状の説明にもある通り、onTimerReady() が呼び出されるまで Player の生成を実行しないことで複数の Player が問題なく動作するようになっています。

* 要望
任意のタイミングで Player を生成しても症状が発生しないよう対応いただけますでしょうか？
また、再生に失敗する場合は requestPlay() が false を返すよう対応いただけますでしょうか？

**Comment by arcatdmz** [comment]
@ya2ha4 お返事遅くなり申し訳ありません。次のバージョンで修正される見込みですので、もう少々お待ちください。

**Comment by arcatdmz** [comment]
この問題は Songle API 由来のものでしたが [v0.4.0](https://scrapbox.io/textalive/TextAlive_App_API%E3%81%AE%E9%96%8B%E7%99%BA%E5%B1%A5%E6%AD%B4#664011a33c16b10000e62ff1) で修正されたと思います。ご確認いただければ幸いです。

**Comment by ya2ha4** [comment]
@arcatdmz 
v.0.4.0 にて修正されていることを確認できました。
ご対応いただきありがとうございました。
