### ISSUE TITLE
Player を複数生成し、同じタイミングで requestPlay() を実行したものの Player ごとに position の差異が発生する

### ISSUE THREAD

**Issue by ya2ha4** [TextAliveJp/textalive-app-api#13]
textalive-app-api (ver.0.3.2) を使用している際に下記の症状が発生しています。

* 症状
表題の通り複数の Player.requestPlay() を同一タイミングで実行しても position の値にズレが発生しています。
これは、Player.timer.position や onTimeUpdate() で取得可能な position いずれのケースでも発生します。

* 再現方法
https://github.com/ya2ha4/TextAliveAppAPI_VerificationCode_2023_11_ver1 にて再現コードを用意していますのでご確認いただけますでしょうか。

* 要望
過去に [Gitter Chat](https://gitter.im/textalive-app-api/community?at=615fc3307db1e3753e2b2469) のやり取りにて言及されていた、ユーザ側でロジックの調整できる環境を提供いただくか、現行の Timer クラスにて対応いただけますでしょうか？

**Comment by arcatdmz** [comment]
@ya2ha4 こちらは再生時にバッファリングなどの処理が生じる可能性もあり、同じタイミングで再生リクエストを発行しても全く同一にはならないことが多い点どうぞご了承ください。
演出にもよりますが、どれか一つのプレイヤーの再生位置を基準に画面表示をコントロールすることが一般的な方針になろうかと思います。
また、あまりに先走ってしまうプレイヤーがいた場合はそれを一時停止することも効果的かもしれません。

そのうえで、ユーザがご自身で新たな `Timer` クラスを実装できる手段に関しては検討させていただきます。
大変お待たせして申し訳ありませんが、何卒よろしくお願いいたします。

**Comment by ya2ha4** [comment]
@arcatdmz 
ご回答ありがとうございました。
再生後は一時停止しない場合、コメントの通り一つのプレイヤーの再生位置を基準にする方法で問題ないかと思いますのでそのように対応いたします。

対応が難しいケースがございましたら改めて issue などでご相談させていただければと思います。
