### ISSUE TITLE
時区間駆動型APIのリファレンス：TimedObjectsInRangeのnextの誤記。直前→直後

### ISSUE THREAD

**Issue by Blue-Tone** [TextAliveJp/textalive-app-api#17]
[時区間駆動型APIのリファレンス：TimedObjectsInRangeのnextの説明](https://developer.textalive.jp/packages/textalive-app-api/interfaces/TimedObjectsInRange.html#next:~:text=%E6%8C%87%E5%AE%9A%E5%8C%BA%E9%96%93%E3%81%AE-,%E7%9B%B4%E5%89%8D,-%E3%81%AB%E3%81%82%E3%82%8B%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%20/%20The%20first)に、誤記と思われるものを見つけたので報告しておきます。
nextは直前ではなく、直後が正解でしょうか？

<img width="592" alt="スクリーンショット 2024-05-18 11 05 15" src="https://github.com/TextAliveJp/textalive-app-api/assets/18328371/5131ef00-e38c-4b3b-8f02-707d655864d4">

**Comment by arcatdmz** [comment]
@Blue-Tone ありがとうございます。実際のドキュメントは自動生成されているので、元のコード内のコメントも同様に修正させていただきます。
