### ISSUE TITLE
TypeScriptでRenderingUnitFunctionのunit引数にtextが定義されていないエラーが出てしまう。

### ISSUE THREAD

**Issue by hota1024** [TextAliveJp/textalive-app-api#2]
TypeScriptでtextalive-app-apiを利用しているのですが、`RenderingUnitFunction`型の関数の第2引数`unit`に`text`にアクセスしようとすると以下のようなエラーが発生しました。

```
Property 'text' does not exist on type 'IRenderingUnit'.ts(2339)
```

コードは以下です。

```ts
const onAnimatePhrase: RenderingUnitFunction = (now, unit) => {
  if (unit.contains(now)) {
    console.log(unit.text) // ここで2339エラー
  }
}
```

**Comment by arcatdmz** [comment]
@hota1024 ご利用ありがとうございます！

`RenderingUnitFunction` 型はそのままだと文字に限らないユニットに使えてしまうため、確かに、型定義に問題がありますね。

とりあえず、以下のように引数を [`ITextUnit`](https://developer.textalive.jp/packages/textalive-app-api/interfaces/itextunit.html) として扱って対処してください。

```
import { ITextUnit, RenderingUnitFunction } from "textalive-app-api";

const onAnimatePhrase: RenderingUnitFunction = (now, unit: ITextUnit) => {
  if (unit.contains(now)) {
    console.log(unit.text);
  }
}
```

また、 `unit` の実際の型を絞り込みたい場合は、 [`UnitTypes`](https://developer.textalive.jp/packages/textalive-app-api/globals.html#unittypes) を使って以下のように書けると思います。

```
import { ITextUnit, RenderingUnitFunction, UnitTypes } from "textalive-app-api";

const onAnimatePhrase: RenderingUnitFunction = (now, unit: ITextUnit) => {
  if (unit.getType() === UnitTypes.CHAR) {
    const char = unit as IChar;
    // ... 文字に対する処理
  }
}
```

次のバージョンで型定義を直すか、ドキュメントを充実させるかしてみます。

ご報告ありがとうございました。

**Comment by hota1024** [comment]
早々のご対応ありがとうございます🙏🏻
了解です。`ITextUnit`で書き直してみます！ありがとうございます！
