### ISSUE TITLE
ITextUnitのadvance、ascent、descentについて

### ISSUE THREAD

**Issue by 7mA** [TextAliveJp/textalive-app-api#4]
インターフェースITextUnitのadvance、ascent、descentプロパティについてお伺いします。
https://developer.textalive.jp/packages/textalive-app-api/interfaces/itextunit.html#advance

これらのプロパティはStyled Textにおいて使われている概念だと思いますが、
実際にこちらの中身を使いたい場合に、予めレンダリングやスタイルの指定はどうなさいますでしょうか？

**Comment by arcatdmz** [comment]
@7mA TextAlive App APIのご利用ありがとうございます！

ご質問のプロパティおよび `color` `font` `fontFamily` `fontSize` `fontStyle` のようなフォント情報に関するプロパティに関しては、大変申し訳ないのですが TextAlive 本サービスサイトで利用されていたもので、 App API では利用できません。

App API を使ったアプリケーション開発では、フォントを含む文字描画の方法はすべて開発者に委ねられており、上記のプロパティはすべて意味を持ちません。ドキュメントの不備ですので、次の patch release で削除いたします。

最新のサンプルコードではCSS（Webフォント）を使って文字のスタイルを指定しています。ぜひ参考にしてみてください。

https://codepen.io/arcatdmz/pen/abNXJgG

![https://gyazo.com/36e0ba955a7d0a80bf2a808e942e080f](https://i.gyazo.com/36e0ba955a7d0a80bf2a808e942e080f.png)

**Comment by 7mA** [comment]
@arcatdmz 休日なのに早速ご回答ありがとうございます！
App API では利用できないことは承知いたしました！
いただいた例を拝見いたします。m(_ _)m

**Comment by arcatdmz** [comment]
ではいったん close させていただきます。また何かあれば遠慮なく re-open, 新しい issue を作成してください！
