### ISSUE TITLE
GET file://api.songle.jp/v2/api.js net::ERR_INVALID_URL

### ISSUE THREAD

**Issue by monaka** [TextAliveJp/textalive-app-api#5]
ファイルシステム上に置いた HTML ファイル経由の JavaScript コードで使おうとすると、console に下記のエラーが出ます。

```
GET file://api.songle.jp/v2/api.js net::ERR_INVALID_URL
```

再現コードは gist に上げました。
https://gist.github.com/monaka/ee2e262ba008713d49717b8cfd7c35b2

再現環境は ChromeOS Version 86.0.4240.112 (Official Build) (64-bit) 。
他の環境でも再現しそうに思います。

URL scheme が file のとき https で置換すれば解決するような気がしますが、他の兼ね合いで Web サーバからの読み込みでないと困る要素があるなら、仕様として明記するのも一案かとは思います。

**Comment by arcatdmz** [comment]
@monaka 返信が遅れて失礼いたしました。また、ご報告ありがとうございます。

同様のご報告を、iOSアプリのWebView上で読み込んだ場合にいただいています。
Songle API のライブラリを `file://` で読み込みたいケースはないはずですので、ご提案のとおり `https://` で読み込むことにして、次の patch release に組み入れたいと思います。

なお、Songle APIを手動で読み込み済みでグローバルな名前空間に `Songle` という変数が定義されている場合、この js ファイルの読み込みプロセス自体が走りません。

したがって、当面の対処としては

```html
<script src="https://api.songle.jp/v2/api.js"></script>
```

のようなコードを HTML ファイル内で TextAlive App API を読み込むより前に記述しておいていただければと思います。

**Comment by monaka** [comment]
@arcatdmz ご案内ありがとうございます。 api.js の明示的なロードで本件が再現しなくなることを手元環境で確認しました。解決済みとしてクローズします。
