### ISSUE TITLE
Example of textalive with Vue ? 

### ISSUE THREAD

**Issue by shilik** [TextAliveJp/textalive-app-api#7]
It is greatly appreciated if you can give an example of how to integrate textalive into Vue framework. Thank you.

**Comment by arcatdmz** [comment]
Thanks for your comment! I created one with React but Vue.

For the past Magical Mirai programming contests, I remember several projects used Vue (and also Svelte) so I'm sure you could find a way... hope somebody provides a concrete example.

**Comment by shilik** [comment]
Thanks for the quick reply, I will look into it. Hopefully someone can
kindly put an basic example of Vue framework.

Jun Kato ***@***.***> 於 2022年4月29日 週五 14:04 寫道：
